dailyfresh/dailyfresh/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/', include('df_user.urls', namespace='df_user')),
    url(r'^goods/', include('df_goods.urls', namespace='df_goods')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^cart/', include('df_cart.urls')),
    url(r'^order/', include('df_order.urls')),
    url(r'^search/', include('haystack.urls')),
]

dailyfresh/df_cart/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.cart, name='cart'),
    url(r'^add(\d+)_(\d+)', views.add, name='add'),
    url(r'^edit(\d+)_(\d+)', views.edit, name='edit'),
    url(r'^delete(\d+)', views.delete, name='delete'),
]

dailyfresh/df_user/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^register/$', views.register, name='register'),
    url(r'^register_handle/$', views.register_handle, 'register_handle'),
    url(r'^login/', views.login, name='login'),
    url(r'^login_handle/', views.login_handle, name='login_handle'),
    url(r'^register_exist/', views.register_exist, name='register_exist'),
    url(r'^info/', views.user_info, name='user_info'),
    url(r'^site/', views.site, name='site'),
    url(r'^order/(\d+)', views.order, name='order'),
    url(r'^logout/', views.logout, name='logout')
]

dailyfresh/df_order/models.py
#coding=utf-8
from django.db import models

#订单信息
class OrderInfo(models.Model):
    oid = models.CharField(max_length=20, primary_key=True)
    user = models.ForeignKey('df_user.UserInfo')
    odate = models.DateTimeField(auto_now=True)
    oIsPay = models.BooleanField(default=False)
    ototal = models.DecimalField(max_digits=6, decimal_places=2)
    oaddress = models.CharField(max_length=150)
    oisdel = models.BooleanField(default=False)

#无法实现：真实支付，物流信息

class OrderDetailInfo(models.Model):
    goods = models.ForeignKey('df_goods.GoodsInfo')
    order = models.ForeignKey('df_order.OrderInfo')
    price = models.DecimalField(max_digits=5, decimal_places=2)
    count = models.IntegerField()

dailyfresh/df_user/models.py
#coding=utf-8
from django.db import models

class UserInfo(models.Model):
    uname=models.CharField(max_length=20)
    upwd=models.CharField(max_length=40)
    uemail=models.CharField(max_length=30)
    ushou=models.CharField(max_length=10, default='')
    uaddress=models.CharField(max_length=100, default='')
    uyoubian=models.CharField(max_length=6, default='')
    uphone=models.CharField(max_length=11, default='')
    #default,black 是python层面的约束，不影响数据库表结构

dailyfresh/df_user/views.py
#coding=utf-8
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.core.paginator import Paginator
from models import *
from hashlib import sha1
from . import user_decorator
from df_goods.models import *
from df_order.models import *
#注册
def register(request):
    return render(request, 'df_user/register.html')
#注册逻辑处理
def register_handle(request):
    #接收用户输入
    post=request.POST
    uname=post.get('user_name')
    upwd=post.get('pwd')
    upwd2=post.get('cpwd')
    uemail=post.get('email')
    # upwd=post.get('allow')
    #判断两次密码
    if upwd!=upwd2:
        return redirect('/user/register/')
    #密码加密
    s1 = sha1()
    s1.update(upwd)
    upwd3 = s1.hexdigest()
    #创建对象
    user=UserInfo()
    user.uname = uname
    user.upwd = upwd3
    user.uemail = uemail
    user.save()
    #注册成功，转到登陆页
    return redirect('/user/login/')
#验证用户名是否存在
def register_exist(request):
    username=request.GET.get('uname')
    # count = UserInfo.objects.filter(uname=username).count()
    count = UserInfo.objects.filter(uname=username).count()
    # context = {'count': count}
    # return render(request, context)
    return JsonResponse({'count': count})

#登录
def login(request):
    uname=request.COOKIES.get('uname', '')
    context={'title': '用户登录', 'error_name':0, 'error_pwd':0, 'uname':uname}
    return render(request, 'df_user/login.html', context)
#登录，接收请求信息
def login_handle(request):
    post=request.POST
    uname=post.get('username')
    upwd=post.get('pwd')
    jizhu=post.get('jizhu', 0)
    users=UserInfo.objects.filter(uname=uname)
    # print uname

    if len(users)==1:
        s1=sha1()
        s1.update(upwd)
        if s1.hexdigest()==users[0].upwd:
            red = HttpResponseRedirect('/user/info/')
            if jizhu!=0:
                red.set_cookie('uname', uname)
            else:
                red.set_cookie('uname', '', max_age=-1)
            # print uname
            request.session['user_id'] = users[0].id
            request.session['user_name'] = uname
            return red
        else:
            context = {'title': '用户登录', 'error_name':0, 'error_pwd': 1, 'uname': uname, 'upwd': upwd}
            return render(request, 'df_user/login.html', context)
    else:
        context = {'title': '用户登录', 'error_name': 1, 'error_pwd': 0, 'uname': uname, 'upwd': upwd}
        return render(request, 'df_user/login.html', context)
#用户中心
@user_decorator.login
def user_info(request):
    username = request.session.get('user_name')
    # print username
    user = UserInfo.objects.filter(uname=username).first()
    goods_ids=request.COOKIES.get('goods_ids', '')
    goods_ids1 = goods_ids.split(',')
    goods_list = []
    if goods_ids != '':
        for goods_id in goods_ids1:
            goods_list.append(GoodsInfo.objects.get(id=int(goods_id)))
    else:
        goods_list = []
    # explain = '无最近浏览'
    context = {'title': '用户中心', 'page_name': 1,
        'user_phone': user.uphone, 'user_address': user.uaddress,
        'user_name': username, 'goods_list': goods_list}
    # print context
    # context = explain
    return render(request, 'df_user/user_center_info.html', context)
#退出登录
def logout(request):
    request.session.flush() #清空当前用户的所有session
    return HttpResponseRedirect('/user/login')
#全部订单
@user_decorator.login
def order(request, index):
    user_id = request.session['user_id']
    orders_list = OrderInfo.objects.filter(user_id=int(user_id)).order_by('-odate')
    paginator = Paginator(orders_list, 2)
    page = paginator.page(int(index))
    context = {
        'paginator': paginator,
        'page': page,
        # 'orders_list':orders_list,
        'title': "用户中心",
        'page_name': 1,
    }
    return render(request, 'df_user/user_center_order.html', context)

#收货地址
@user_decorator.login
def site(request):
    user = UserInfo.objects.get(id=request.session['user_id'])
    if request.method == "POST":
        user.ushou = request.POST.get('ushou')
        user.uaddress = request.POST.get('uaddress')
        user.uyoubian = request.POST.get('uyoubian')
        user.uphone = request.POST.get('uphone')
        user.save()
    context = {
        'page_name': 1,
        'title': '用户中心',
        'user': user,
    }
    return render(request, 'df_user/user_center_site.html', context)

dailyfresh/templates/df_user/login.html
{% extends 'base_foot.html' %}
{%block head%}
<script>
	$(function () {
		name_error=false;
		pwd_error=false;

		if({{error_name}}==1){
			$('.user_error').html('用户名错误').show();
		}
		if ({{error_pwd}}==1){
			$('.pwd_error').html('密码错误').show();
		}
		$('.name_input').blur(function (){
			if($('.name_input').val().length==0){
				$('.user_error').html('请填写用户名').show();
			}else{
				$('.user_error').hide();
				name_error=true;
			}
		});
		$('.pass_input').blur(function () {
			if($(this).val().length==0){
				$('.pwd_input').html('请输入密码').show();
				pwd_error=false;
			}else{
				$('.pwd_error').hide();
				pwd_error=true;
			}
		});
		// $('form').submit(function () {
	})
</script>
{% endblock head %}
{% block body %}
	<div class="login_top clearfix">
		<a href="index.html" class="login_logo"><img src="/static/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="/user/register/">立即注册</a>
				</div>
				<div class="form_input">
					<form action="/user/login_handle/" method="post">
						{%csrf_token%}
						<input type="text" name="username" class="name_input" value="{{uname}}" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" value="{{upwd}}" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="jizhu" value="1" checked="checked">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock body %}

dailyfresh/templates/df_user/register.html
{% extends 'base_foot.html' %}

{%block head%}
<script type="text/javascript" src="/static/js/register.js"></script>

{%endblock head%}

{%block body%}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="/static/images/logo02.png"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="/user/login/">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form action="/user/register_handle/" method="post">
					{%csrf_token%}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册">
					</li>
				</ul>				
				</form>
			</div>

		</div>

	</div>
{%endblock body%}

dailyfresh/templates/df_user/user_center_info.html
{% extends 'base.html' %}

{% block center_body %}


	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info/" class="active">· 个人信息</a></li>
				<li><a href="/user/order/1">· 全部订单</a></li>
				<li><a href="/user/site/">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ user_name }}</li>
							<li><span>联系方式：</span>{{ user_phone }}</li>
							<li><span>联系地址：</span>{{ user_address }}</li>
						</ul>
				</div>
            <h3 class="common_title2">{{ context.explain }}</h3>
            <div class="has_view_list">
                <ul class="goods_type_list clearfix">
                    {%  for good in goods_list %}
                    <li>
                        <a href="/goods/{{ good.id }}/"><img src="/static/{{ good.gpic }}"></a>
                        <h4><a href="/goods/{{ good.id }}/">{{ good.gtitle }}</a></h4>
                        <div class="operate">
                            <span class="prize">￥{{ good.gprice }}</span>
                            <span class="unit">{{ good.gprice }}/{{ good.gunit }}</span>
                            <a href="/cart/add{{ good.id }}_1/" class="add_goods" title="加入购物车"></a>
                        </div>
                    </li>
                    {% endfor %}
			</ul>
            </div>
		</div>
	</div>
{% endblock center_body %}

dailyfresh/templates/df_user/user_center_order.html
{% extends 'base.html' %}

{% block center_body %}


	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info/">· 个人信息</a></li>
				<li><a href="/user/order/1" class="active">· 全部订单</a></li>
				<li><a href="/user/site/">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
                {% for orderinfo in page %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ orderinfo.odate|date }}</li>
					<li class="col02">订单号：{{ orderinfo.oid }}</li>
					<li class="col02 stress">已支付</li>
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
                                {% for order_detail in orderinfo.orderdetailinfo_set.all %}
								<ul class="order_goods_list clearfix">
									<li class="col01"><img src="/static/{{ order_detail.goods.gpic }}"></li>
                                    <li class="col02">{{ order_detail.goods.gtitle }}<em class="good_price">{{ order_detail.goods.gprice }}</em>元/<em>{{ order_detail.goods.gunit }}</em></li>
									<li class="col03">{{ order_detail.count }}件</li>
									<li class="col04">11.80元</li>
								</ul>
                                {% endfor %}
							</td>
							<td width="15%">{{ orderinfo.ototal }}元</td>
							<td width="15%">已付款</td>
							<td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
						</tr>
					</tbody>
				</table>
			    {% endfor %}


				<div class="pagenation">
                    {% if page.has_previous %}
					    <a href="/order/page.previous_page_number">上一页</a>
                    {% endif %}

                    {% for index in paginator.page_range %}
                        {% if index == page.number %}
                            <a href="/user/order/previous_page_number" class="active">{{ index }}</a>
                        {% else %}
                            <a href="/user/order/previous_page_number">{{ index }}</a>
                        {% endif %}
                    {% endfor %}

                    {% if page.has_next %}
					    <a href="/user/order/1" page.next_page_number %}">下一页></a>
                    {% endif %}
				</div>
		</div>
	</div>

    <script type="text/javascript">
    $(function () {
        $('.col04').each(function () {
            count = $(this).prev().text();
            price = $(this).prev().prev().find('.good_price').text();
            $(this).html(parseFloat(count,2)*parseFloat(price,2)+'元');
            }

        )
        }
    )

    </script>
{% endblock center_body %}

dailyfresh/templates/df_user/user_center_site.html
{% extends 'base.html' %}

{% block center_body %}


	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
                <li><a href="/user/info/">· 个人信息</a></li>
				<li><a href="/user/order/1">· 全部订单</a></li>
				<li><a href="/user/site/" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
                        <dt>收件人：{{ user.ushou }}</dt>
                        <dt>电话：{{ user.uphone }}</dt>
                        <dt>当前地址：{{ user.uaddress }}</dt>
{#                        <a href="/user/place_order" style="display: block; width: 80px; height:30px; line-height: 30px; text-align: center;font-size: 13px; " class="info_submit">提交订单</a>#}
					</dl>
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form action='/user/site/' method="post">
                        {% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="ushou" value="{{ user.ushou }}">
						</div>
                        <div class="form_group">
                            <label>手机：</label>
                            <input type="text" name="uphone" value="{{ user.uphone }}">
                        </div>
                        <div class="form_group">
                            <label>邮编：</label>
                            <input type="text" name="uyoubian" value="{{ user.uyoubian }}">
                        </div>
                        <div class="form_group form_group2">
                            <label>详细地址：</label>
                            <textarea class="site_area" name="uaddress" >{{ user.uaddress }}</textarea>
                        </div>
						<input type="submit" name="" value="修改地址" class="info_submit">
					</form>
				</div>
		</div>
	</div>


{% endblock center_body %}